SEMANTIC_TAXONOMY:
  CLUSTER_METHODS:
    strict_kmeans: KMeans
    strict_agglom: AgglomerativeClustering
    strict_kmeans_imb: KMeans
    imbalanced: KMeans
    imbalanced_test: KMeans
    fuzzy_kmeans: KMeans
    fuzzy_agglom: AgglomerativeClustering
    fuzzy_dbscan: DBSCAN
    fuzzy_hdbscan: HDBSCAN
    dendrogram: AgglomerativeClustering
    centroids: KMeans
    centroids_test: KMeans
  CLUSTER_CONFIGS:
    strict_kmeans:
      - n_clusters: 5 # level 1
        n_init: 5
      - n_clusters: 20 # level 2
        n_init: 5
      - n_clusters: 20 # level 3
        n_init: 5
      - n_clusters: 40 # level 4
        n_init: 5
    strict_agglom:
      - n_clusters: 5
      - n_clusters: 20
      - n_clusters: 20
      - n_clusters: 40
    strict_kmeans_imb:
      - n_clusters: 5
        n_init: 5
      - n_clusters: 20
        n_init: 5
      - n_clusters: 20
        n_init: 5
      - n_clusters: 40
        n_init: 5
    fuzzy_kmeans:
      - n_clusters: 5
        n_init: 5
      - n_clusters: 20
        n_init: 5
      - n_clusters: 20
        n_init: 5
      - n_clusters: 40
        n_init: 5
    fuzzy_agglom:
      - n_clusters: 5
      - n_clusters: 20
      - n_clusters: 20
      - n_clusters: 40
    fuzzy_dbscan:
      - eps:
          - 0.15
          - 0.25
        min_samples:
          - 8
          - 16
    fuzzy_hdbscan:
      - min_cluster_size:
          - 4
          - 8
        min_samples:
          - 8
          - 16
    dendrogram:
      - n_clusters: 100
    centroids:
      - n_clusters: # level 4
        n_init: 5
        centroids: False
      - n_clusters: # level 3
        n_init: 5
        centroids: True
      - n_clusters: # level 2
        n_init: 5
        centroids: True
      - n_clusters: # level 1
        n_init: 5
        centroids: True
  SINGLE_CLUSTER_CONFIGS:
    centroids:
      - n_clusters: 10000 # level 5
        n_init: 5
        centroids: False
      - n_clusters: 2500 # level 4
        n_init: 5
        centroids: True
      - n_clusters: 1000 # level 3
        n_init: 5
        centroids: True
      - n_clusters: 200 # level 2
        n_init: 5
        centroids: True
      - n_clusters: 25 # level 1
        n_init: 5
        centroids: True
    centroids_test:
      - n_clusters: 200 # level 3
        n_init: 5
        centroids: False
      - n_clusters: 50 # level 2
        n_init: 5
        centroids: True
      - n_clusters: 10 # level 1
        n_init: 5
        centroids: True
    imbalanced:
      - n_clusters: 25
        n_init: 5
      - n_clusters: 200
        n_init: 5
      - n_clusters: 1000
        n_init: 5
      - n_clusters: 2500
        n_init: 5
      - n_clusters: 10000
        n_init: 5
    imbalanced_test:
      - n_clusters: 25
        n_init: 5
      - n_clusters: 100
        n_init: 5
  DF_CONFIGS:
    kmeans_strict:
      name: kmeans_strict
      label: _strict
      cumulative: True
    agglom_strict:
      name: agglom_strict
      label: _strict
      cumulative: True
    kmeans_strict_imb:
      name: semantic_imbalanced
      label: _strict
    imbalanced:
      name: semantic_imbalanced
      label: _strict
      cumulative: True
    imbalanced_test:
      name: semantic_imbalanced
      label: _strict
      cumulative: True
    kmeans_fuzzy:
      name: kmeans_fuzzy
      label: _strict
      cumulative: True
    agglom_fuzzy:
      name: agglom_fuzzy
      label: _strict
      cumulative: True
    agglom_dendrogram:
      name: agglom_dendrogram
      label: _strict
      cumulative: True
    centroids:
      name: semantic_centroids
      label: _centroids
      cumulative: False
    centroids_test:
      name: semantic_centroids
      label: _centroids
      cumulative: False
