humanities:
  history: [
    "History of Europe", 
    "Ancient Egypt",
    "Stone Age",
    "History of China",
    "Carthage"]
  ethics:
    [
      "Applied ethics",
      "Environmental ethics",
      "Animal rights",
      "Bioethics",
      "Normative ethics"
    ]
social_science:
  economics:
    [
      "Econometrics",
      "Macroeconomics",
      "Behavioral economics",
      "Political economy",
      "Social choice theory"
    ]
  physical_geography:
    [
      "Geophysics",
      "Climatology",
      "Hydrology",
      "Oceanography",
      "Lithology"
    ]
  sociology_area_studies:
    [
      "African studies",
      "German studies",
      "Egyptology",
      "Sinology",
      "Iranian studies"
    ]
natural_science:
  biology:
    [
      "Bioinformatics",
      "Cryobiology",
      "Epigenetics",
      "Limnology",
      "Clinical pathology"
    ]
  chemistry:
    [
      "Geochemistry",
      "Pharmacology",
      "Biochemistry",
      "Chemical engineering",
      "Thermochemistry"
    ]
  physics:
    [
      "Astrophysics",
      "Electricity",
      "Fluid dynamics",
      "Molecular physics",
      "Aerodynamics"
    ]
formal_science:
  computer_science:
    [
      "Machine learning",
      "Automated reasoning",
      "Information retrieval",
      "Parallel computing",
      "Robotics"
    ]
  mathematics:
    [
      "Probability theory",
      "Proof theory",
      "Linear algebra",
      "Convex geometry",
      "Number theory"
    ]
applied_science:
  chemical_engineering:
    [
      "Catalysis",
      "Nanotechnology",
      "Biochemical engineering",
      "Nuclear engineering",
      "Transport phenomena"
    ]
  systems_science:
    [
      "Control theory",
      "System dynamics",
      "Cybernetics",
      "Chaos theory",
      "Systems biology"
    ]
  electrical_engineering:
    [
      "Semiconductor",
      "Quantum computing",
      "Information theory",
      "Mechatronics",
      "Photonics"
    ]